apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.20.2
        name: nginx
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
        ports:
        - containerPort: 80
          name: nginx
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
